Type: Jupyter Notebook Extension
Name: HiGlass for Jupyter
Description: HiGlass for your Jupyter Notebooks
Link: readme.md
Icon: higlass-logo.png
Main: extension.js
Compatibility: 4.x, 5.x
Parameters:
  - name: example_parameter
    description: Number of characters to limit output to
    input_type: number
    default: 10000
    step: 1
    min: 0

